// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:tayar_app/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // ====== التطبيق (الراكب/الطيار) يدعم Android و iOS بس. الويب ملوش
  // استخدام هنا - لوحة الأدمن صفحة HTML منفصلة (tayar-admin/public)
  // ومش شغالة بكود Flutter ده خالص ======
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvv6t5H7pdmWmqDzwQ1SRo3gyWYzFuWrI',
    appId: '1:354477388400:ios:e2a0f27cbe68e736c23ab5',
    messagingSenderId: '354477388400',
    projectId: 'b10-app-1e682',
    storageBucket: 'b10-app-1e682.firebasestorage.app',
    iosBundleId: 'com.example.tayayApp',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7CW-3rCVG5lIesTWU_envKbZkNd5zyBQ',
    appId: '1:354477388400:android:f05fcd5a91d70396c23ab5',
    messagingSenderId: '354477388400',
    projectId: 'b10-app-1e682',
    storageBucket: 'b10-app-1e682.firebasestorage.app',
  );
}
